# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  # Repositories to recieve changes
  repos: |
    jhudsl/ITCR_Documentation_and_Usability
    jhudsl/ITCR_Cancer_Research_Leadership
    jhudsl/ITCR_Data_Management
#ADD NEW REPO HERE following the format above#
  files:
    - source: .github/workflows/docker-build-test.yml
      dest: .github/workflows/docker-build-test.yml
    - source: .github/workflows/transfer-rendered-files.yml
      dest: .github/workflows/transfer-rendered-files.yml
    - source: .github/workflows/style-and-sp-check.yml
      dest: .github/workflows/style-and-sp-check.yml
    - source: .github/workflows/url-checker.yml
      dest: .github/workflows/url-checker.yml
    - source: .github/workflows/release-notes.yml
      dest: .github/workflows/release-notes.yml
    - source: scripts/
      dest: scripts/
    - source: docker/
      dest: docker/
    - source: .gitignore
      dest: .gitignore

###### TO ADD NEW REPOSITORY USE THIS FORMAT; Feel free to add/drop files that
# you specifically would like synced (or not).
#
#  # Repositories to receive changes
#  repos: |
#    org/repo_name
#  # Files which should be updated
#  - source: .github/workflows/
  #   dest: .github/workflows/
  # - source: scripts/
  #   dest: scripts/
  # - source: docker/
  #   dest: docker/
  # - source: .gitignore
  #   dest: .gitignore
