# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  # Repositories to recieve changes
  repos: |
    jhudsl/ITCR_Documentation_and_Usability
    jhudsl/ITCR_Cancer_Research_Leadership
#ADD NEW REPO HERE following the format above#
  # Files which should be updated
  files:
  - .gitignore
  - .github/workflows/render-bookdown.yml
  - .github/workflows/style-and-sp-check.yml
  - .github/workflows/url-checker.yml
  - .github/workflows/ISSUE_TEMPLATES/issue_template.md
  - .github/workflows/PULL_REQUEST_TEMPLATE.md
  - docker/*
  - scripts/*
  - getting_started.md

###### TO ADD NEW REPOSITORY USE THIS FORMAT; Feel free to add/drop files that
# you specifically would like synced (or not).
#
#  # Repositories to receive changes
#  repos: |
#    org/repo_name
#  # Files which should be updated
#  files:
#  - .gitignore
#  - .github/workflows/render-leanpub.yml
#  - .github/workflows/sp-check.yml
#  - .github/workflows/url-checker.yml
#  - .github/workflows/ISSUE_TEMPLATES/issue_template.md
#  - .github/workflows/PULL_REQUEST_TEMPLATE.md
#  - scripts/*
#  - getting_started.md
