FROM rocker/tidyverse
LABEL maintainer="cansav09@gmail.com"

# Install apt-getable packages to start
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils dialog

RUN apt-get install -y --no-install-recommends \
    libxt6 \
    libpoppler-cpp-dev \
    vim \
    libglpk40 \
    curl \
    gpg

# Install R
RUN apt-get update && apt-get install -y r-base curl

# Install R packages
RUN Rscript -e  "install.packages( \
    c('curl', \
      'optparse', \
      'gitcreds', \
      'htm2txt', \
      'httr', \
      'jsonlite', \
      'rvest', \
      'stringi', \
      'textrank', \
      'udpipe', \
      'xml2', \
      'knitr', \
      'igraph', \
      'rprojroot', \
      'webshot'))"

# Install phantomjs
RUN Rscript -e "webshot::install_phantomjs()"

# Install cow
RUN Rscript -e "install.packages('https://github.com/jhudsl/cow/raw/main/package_bundles/cow_0.0.0.9000.tgz', repos = NULL)"
