FROM rocker/tidyverse
LABEL maintainer="cansav09@gmail.com"

RUN apt-get update && apt-get install -y wkhtmltopdf

# Install R
RUN apt-get update && apt-get install -y r-base curl

# Install R packages
RUN Rscript -e  "install.packages( \
    c('curl', \
      'optparse', \
      'gitcreds', \
      'htm2txt', \
      'httr', \
      'jsonlite', \
      'rvest', \
      'stringi', \
      'textrank', \
      'udpipe', \
      'xml2', \
      'knitr', \
      'igraph', \
      'rprojroot'))"

# Copy over git token and package list
COPY git_token.txt .

# Install cow
RUN Rscript -e "remotes::install_github('jhudsl/cow', auth_token = readLines('git_token.txt'))"
RUN rm git_token.txt
